### ISSUE TITLE
cargo install failed due to "error[E0658]: use of unstable library feature `file_lock`"

### ISSUE THREAD

**Issue by pengshaoxing** [j178/prek#584]
Hi, I'm trying to install the prek binary file to my WSL by the carogo way, but encountering this error:
```shell 

➜  ~ cargo install --locked --git https://github.com/j178/prek
....
....
error[E0658]: use of unstable library feature `file_lock`
  --> src/fs.rs:53:35
   |
53 |                 if !matches!(err, std::fs::TryLockError::WouldBlock) {
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #130994 <https://github.com/rust-lang/rust/issues/130994> for more information

error[E0658]: use of unstable library feature `file_lock`
  --> src/fs.rs:46:27
   |
46 |         match file.file().try_lock() {
   |                           ^^^^^^^^
   |
   = note: see issue #130994 <https://github.com/rust-lang/rust/issues/130994> for more information

error[E0658]: use of unstable library feature `file_lock`
  --> src/fs.rs:61:29
   |
61 |                 file.file().lock().map_err(|err| {
   |                             ^^^^
   |
   = note: see issue #130994 <https://github.com/rust-lang/rust/issues/130994> for more information

error[E0658]: use of unstable library feature `file_lock`
   --> src/fs.rs:101:41
    |
101 |         if let Err(err) = self.0.file().unlock() {
    |                                         ^^^^^^
    |
    = note: see issue #130994 <https://github.com/rust-lang/rust/issues/130994> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `prek` (bin "prek") due to 4 previous errors
error: failed to compile `prek v0.1.4 (https://github.com/j178/prek#f77f444a)`, intermediate artifacts can be found at `/tmp/cargo-install2U3EIG`.
 ```
System: WSL(Ubuntu 24.04 LTS)
Rust version: 
```shell
➜  ~ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/peng/.rustup

installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu (active, default)

active toolchain
----------------
name: stable-x86_64-unknown-linux-gnu
active because: it's the default toolchain
installed targets:
  x86_64-unknown-linux-gnu
➜  ~ rustc --version
rustc 1.88.0 (6b00bc388 2025-06-23)
```

**Comment by j178** [comment]
You need Rust 1.89 to build prek, as listed in the `rust-toolchain.toml` file. https://github.com/j178/prek/blob/master/rust-toolchain.toml

**Comment by pengshaoxing** [comment]
Thanks, compiling is ok now after updating the Rust version to 1.89 according to the `rust-toolchain.toml` file.
